language: cpp

env:
# build openrpt .so,        then csvimp and qt-client use the result
 - BUILD_SHARED_LIBS=true   USE_SHARED_OPENRPT=true

before_install:
 - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libdmtx-dev

compiler:
  - gcc
# - clang

before_script:
  - cd ..
  - git clone -b 4_10_x https://github.com/xtuple/qt-client.git
  - cd qt-client
  - git submodule update --init --recursive
  - cd openrpt
  - qmake && make -j4
  - cd .. && qmake
  - cd common && qmake && make -j4
  - cd ../../updater

script:
  - qmake && make -j4
